version: '3.7'
services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - .\config:/consul/config
      - .\data:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - esnetwork
    container_name: consul  

networks:
    esnetwork:
        driver: bridge